version: '3'

services:
  chirpstack-ran-bridge:
    build: .
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}

      - CHIRPSTACK_TENANT_ID=${CHIRPSTACK_TENANT_ID:-52f14cd4-c6f1-4fbd-8f87-4025e1d49242}
      - CHIRPSTACK_API_TOKEN
      - CHIRPSTACK_GATEWAY_ID
      - CHIRPSTACK_API_GRPC_HOST=${CHIRPSTACK_API_GRPC_HOST:-chirpstack}
      - CHIRPSTACK_API_GRPC_PORT=${CHIRPSTACK_API_GRPC_PORT:-8080}
      - CHIRPSTACK_API_GRPC_SECURE

      - CHIRPSTACK_MQTT_SERVER_URI=${CHIRPSTACK_MQTT_SERVER_URI:-mqtt://mosquitto:1883}

      - CHIRPSTACK_DEVICES_REFRESH_PERIOD=${CHIRPSTACK_DEVICES_REFRESH_PERIOD:-300}

      - RAN_TOKEN
      - RAN_COVERAGE_DOMAIN=${RAN_COVERAGE_DOMAIN:-dev}
    logging:
      driver: 'json-file'
      options:
        max-size: "100m"
        max-file: "1"
    depends_on:
      - chirpstack

